import 'country.dart';

/// A ready-to-use list of countries/territories with their dialing codes.
///
/// This is only the *default*. Every widget in this package accepts a
/// `countries` override, so you can replace, trim, reorder, or extend this
/// list freely (e.g. to add territories not listed here, or to change
/// translations) without forking the package.
///
/// Every entry ships display-name translations for all locales this
/// package bundles messages for out of the box: Farsi (`fa`), Arabic
/// (`ar`), Pashto (`ps`), and Urdu (`ur`).
const List<Country> defaultCountries = [
  Country(isoCode: 'AF', dialCode: '93', nameEn: 'Afghanistan', maxLength: 9, translations: {'fa': 'افغانستان', 'ar': 'أفغانستان', 'ps': 'افغانستان', 'ur': 'افغانستان'}),
  Country(isoCode: 'AL', dialCode: '355', nameEn: 'Albania', translations: {'fa': 'آلبانی', 'ar': 'ألبانيا', 'ps': 'البانیا', 'ur': 'البانیا'}),
  Country(isoCode: 'DZ', dialCode: '213', nameEn: 'Algeria', maxLength: 9, translations: {'fa': 'الجزایر', 'ar': 'الجزائر', 'ps': 'الجزایر', 'ur': 'الجزائر'}),
  Country(isoCode: 'AD', dialCode: '376', nameEn: 'Andorra', maxLength: 6, translations: {'fa': 'آندورا', 'ar': 'أندورا', 'ps': 'اندورا', 'ur': 'انڈورا'}),
  Country(isoCode: 'AO', dialCode: '244', nameEn: 'Angola', maxLength: 9, translations: {'fa': 'آنگولا', 'ar': 'أنغولا', 'ps': 'انگولا', 'ur': 'انگولا'}),
  Country(isoCode: 'AR', dialCode: '54', nameEn: 'Argentina', maxLength: 10, translations: {'fa': 'آرژانتین', 'ar': 'الأرجنتين', 'ps': 'ارجنتاین', 'ur': 'ارجنٹائن'}),
  Country(isoCode: 'AM', dialCode: '374', nameEn: 'Armenia', maxLength: 8, translations: {'fa': 'ارمنستان', 'ar': 'أرمينيا', 'ps': 'ارمنستان', 'ur': 'آرمینیا'}),
  Country(isoCode: 'AU', dialCode: '61', nameEn: 'Australia', maxLength: 9, translations: {'fa': 'استرالیا', 'ar': 'أستراليا', 'ps': 'آسټرالیا', 'ur': 'آسٹریلیا'}),
  Country(isoCode: 'AT', dialCode: '43', nameEn: 'Austria', maxLength: 11, translations: {'fa': 'اتریش', 'ar': 'النمسا', 'ps': 'اتریش', 'ur': 'آسٹریا'}),
  Country(isoCode: 'AZ', dialCode: '994', nameEn: 'Azerbaijan', maxLength: 9, translations: {'fa': 'آذربایجان', 'ar': 'أذربيجان', 'ps': 'آذربایجان', 'ur': 'آذربائیجان'}),
  Country(isoCode: 'BH', dialCode: '973', nameEn: 'Bahrain', maxLength: 8, translations: {'fa': 'بحرین', 'ar': 'البحرين', 'ps': 'بحرین', 'ur': 'بحرین'}),
  Country(isoCode: 'BD', dialCode: '880', nameEn: 'Bangladesh', maxLength: 10, translations: {'fa': 'بنگلادش', 'ar': 'بنغلاديش', 'ps': 'بنگله دیش', 'ur': 'بنگلہ دیش'}),
  Country(isoCode: 'BY', dialCode: '375', nameEn: 'Belarus', maxLength: 9, translations: {'fa': 'بلاروس', 'ar': 'بيلاروسيا', 'ps': 'بیلاروس', 'ur': 'بیلاروس'}),
  Country(isoCode: 'BE', dialCode: '32', nameEn: 'Belgium', maxLength: 9, translations: {'fa': 'بلژیک', 'ar': 'بلجيكا', 'ps': 'بلجیم', 'ur': 'بیلجیم'}),
  Country(isoCode: 'BZ', dialCode: '501', nameEn: 'Belize', maxLength: 7, translations: {'fa': 'بلیز', 'ar': 'بليز', 'ps': 'بلیز', 'ur': 'بیلیز'}),
  Country(isoCode: 'BJ', dialCode: '229', nameEn: 'Benin', maxLength: 8, translations: {'fa': 'بنین', 'ar': 'بنين', 'ps': 'بنین', 'ur': 'بینن'}),
  Country(isoCode: 'BT', dialCode: '975', nameEn: 'Bhutan', maxLength: 8, translations: {'fa': 'بوتان', 'ar': 'بوتان', 'ps': 'بوتان', 'ur': 'بھوٹان'}),
  Country(isoCode: 'BO', dialCode: '591', nameEn: 'Bolivia', maxLength: 8, translations: {'fa': 'بولیوی', 'ar': 'بوليفيا', 'ps': 'بولیویا', 'ur': 'بولیویا'}),
  Country(isoCode: 'BA', dialCode: '387', nameEn: 'Bosnia and Herzegovina', maxLength: 8, translations: {'fa': 'بوسنی و هرزگوین', 'ar': 'البوسنة والهرسك', 'ps': 'بوسنیا او هرزیګوینا', 'ur': 'بوسنیا و ہرزیگووینا'}),
  Country(isoCode: 'BW', dialCode: '267', nameEn: 'Botswana', maxLength: 8, translations: {'fa': 'بوتسوانا', 'ar': 'بوتسوانا', 'ps': 'بوتسوانا', 'ur': 'بوٹسوانا'}),
  Country(isoCode: 'BR', dialCode: '55', nameEn: 'Brazil', maxLength: 11, translations: {'fa': 'برزیل', 'ar': 'البرازيل', 'ps': 'برازیل', 'ur': 'برازیل'}),
  Country(isoCode: 'BN', dialCode: '673', nameEn: 'Brunei', maxLength: 7, translations: {'fa': 'برونئی', 'ar': 'بروناي', 'ps': 'بروني', 'ur': 'برونائی'}),
  Country(isoCode: 'BG', dialCode: '359', nameEn: 'Bulgaria', maxLength: 9, translations: {'fa': 'بلغارستان', 'ar': 'بلغاريا', 'ps': 'بلغاریا', 'ur': 'بلغاریہ'}),
  Country(isoCode: 'BF', dialCode: '226', nameEn: 'Burkina Faso', maxLength: 8, translations: {'fa': 'بورکینافاسو', 'ar': 'بوركينا فاسو', 'ps': 'بورکینا فاسو', 'ur': 'برکینا فاسو'}),
  Country(isoCode: 'BI', dialCode: '257', nameEn: 'Burundi', maxLength: 8, translations: {'fa': 'بوروندی', 'ar': 'بوروندي', 'ps': 'بروندي', 'ur': 'برونڈی'}),
  Country(isoCode: 'KH', dialCode: '855', nameEn: 'Cambodia', maxLength: 9, translations: {'fa': 'کامبوج', 'ar': 'كمبوديا', 'ps': 'کمبودیا', 'ur': 'کمبوڈیا'}),
  Country(isoCode: 'CM', dialCode: '237', nameEn: 'Cameroon', maxLength: 9, translations: {'fa': 'کامرون', 'ar': 'الكاميرون', 'ps': 'کامرون', 'ur': 'کیمرون'}),
  Country(isoCode: 'CA', dialCode: '1', nameEn: 'Canada', maxLength: 10, translations: {'fa': 'کانادا', 'ar': 'كندا', 'ps': 'کاناډا', 'ur': 'کینیڈا'}),
  Country(isoCode: 'CL', dialCode: '56', nameEn: 'Chile', maxLength: 9, translations: {'fa': 'شیلی', 'ar': 'تشيلي', 'ps': 'چیلي', 'ur': 'چلی'}),
  Country(isoCode: 'CN', dialCode: '86', nameEn: 'China', maxLength: 11, translations: {'fa': 'چین', 'ar': 'الصين', 'ps': 'چین', 'ur': 'چین'}),
  Country(isoCode: 'CO', dialCode: '57', nameEn: 'Colombia', maxLength: 10, translations: {'fa': 'کلمبیا', 'ar': 'كولومبيا', 'ps': 'کولمبیا', 'ur': 'کولمبیا'}),
  Country(isoCode: 'CR', dialCode: '506', nameEn: 'Costa Rica', maxLength: 8, translations: {'fa': 'کاستاریکا', 'ar': 'كوستاريكا', 'ps': 'کوستاریکا', 'ur': 'کوسٹاریکا'}),
  Country(isoCode: 'HR', dialCode: '385', nameEn: 'Croatia', maxLength: 9, translations: {'fa': 'کرواسی', 'ar': 'كرواتيا', 'ps': 'کرواشیا', 'ur': 'کروشیا'}),
  Country(isoCode: 'CU', dialCode: '53', nameEn: 'Cuba', maxLength: 8, translations: {'fa': 'کوبا', 'ar': 'كوبا', 'ps': 'کیوبا', 'ur': 'کیوبا'}),
  Country(isoCode: 'CY', dialCode: '357', nameEn: 'Cyprus', maxLength: 8, translations: {'fa': 'قبرس', 'ar': 'قبرص', 'ps': 'قبرص', 'ur': 'قبرص'}),
  Country(isoCode: 'CZ', dialCode: '420', nameEn: 'Czech Republic', maxLength: 9, translations: {'fa': 'جمهوری چک', 'ar': 'جمهورية التشيك', 'ps': 'چک جمهوریت', 'ur': 'جمہوریہ چیک'}),
  Country(isoCode: 'DK', dialCode: '45', nameEn: 'Denmark', maxLength: 8, translations: {'fa': 'دانمارک', 'ar': 'الدنمارك', 'ps': 'ډنمارک', 'ur': 'ڈنمارک'}),
  Country(isoCode: 'DJ', dialCode: '253', nameEn: 'Djibouti', maxLength: 8, translations: {'fa': 'جیبوتی', 'ar': 'جيبوتي', 'ps': 'جیبوتي', 'ur': 'جبوتی'}),
  Country(isoCode: 'DO', dialCode: '1809', nameEn: 'Dominican Republic', maxLength: 10, translations: {'fa': 'جمهوری دومینیکن', 'ar': 'جمهورية الدومينيكان', 'ps': 'ډومینیکن جمهوریت', 'ur': 'جمہوریہ ڈومینیکن'}),
  Country(isoCode: 'EC', dialCode: '593', nameEn: 'Ecuador', maxLength: 9, translations: {'fa': 'اکوادور', 'ar': 'الإكوادور', 'ps': 'اکوادور', 'ur': 'ایکواڈور'}),
  Country(isoCode: 'EG', dialCode: '20', nameEn: 'Egypt', maxLength: 10, translations: {'fa': 'مصر', 'ar': 'مصر', 'ps': 'مصر', 'ur': 'مصر'}),
  Country(isoCode: 'SV', dialCode: '503', nameEn: 'El Salvador', maxLength: 8, translations: {'fa': 'السالوادور', 'ar': 'السلفادور', 'ps': 'ال سالوادور', 'ur': 'ایل سیلواڈور'}),
  Country(isoCode: 'EE', dialCode: '372', nameEn: 'Estonia', maxLength: 8, translations: {'fa': 'استونی', 'ar': 'إستونيا', 'ps': 'استونیا', 'ur': 'استونیا'}),
  Country(isoCode: 'ET', dialCode: '251', nameEn: 'Ethiopia', maxLength: 9, translations: {'fa': 'اتیوپی', 'ar': 'إثيوبيا', 'ps': 'ایتوپیا', 'ur': 'ایتھوپیا'}),
  Country(isoCode: 'FJ', dialCode: '679', nameEn: 'Fiji', maxLength: 7, translations: {'fa': 'فیجی', 'ar': 'فيجي', 'ps': 'فیجي', 'ur': 'فجی'}),
  Country(isoCode: 'FI', dialCode: '358', nameEn: 'Finland', maxLength: 10, translations: {'fa': 'فنلاند', 'ar': 'فنلندا', 'ps': 'فینلینډ', 'ur': 'فن لینڈ'}),
  Country(isoCode: 'FR', dialCode: '33', nameEn: 'France', maxLength: 9, translations: {'fa': 'فرانسه', 'ar': 'فرنسا', 'ps': 'فرانسه', 'ur': 'فرانس'}),
  Country(isoCode: 'GE', dialCode: '995', nameEn: 'Georgia', maxLength: 9, translations: {'fa': 'گرجستان', 'ar': 'جورجيا', 'ps': 'ګرجستان', 'ur': 'جارجیا'}),
  Country(isoCode: 'DE', dialCode: '49', nameEn: 'Germany', maxLength: 11, translations: {'fa': 'آلمان', 'ar': 'ألمانيا', 'ps': 'آلمان', 'ur': 'جرمنی'}),
  Country(isoCode: 'GH', dialCode: '233', nameEn: 'Ghana', maxLength: 9, translations: {'fa': 'غنا', 'ar': 'غانا', 'ps': 'غانا', 'ur': 'گھانا'}),
  Country(isoCode: 'GR', dialCode: '30', nameEn: 'Greece', maxLength: 10, translations: {'fa': 'یونان', 'ar': 'اليونان', 'ps': 'یونان', 'ur': 'یونان'}),
  Country(isoCode: 'GT', dialCode: '502', nameEn: 'Guatemala', maxLength: 8, translations: {'fa': 'گواتمالا', 'ar': 'غواتيمالا', 'ps': 'ګواتیمالا', 'ur': 'گوئٹے مالا'}),
  Country(isoCode: 'GN', dialCode: '224', nameEn: 'Guinea', maxLength: 9, translations: {'fa': 'گینه', 'ar': 'غينيا', 'ps': 'ګیني', 'ur': 'گنی'}),
  Country(isoCode: 'HT', dialCode: '509', nameEn: 'Haiti', maxLength: 8, translations: {'fa': 'هائیتی', 'ar': 'هايتي', 'ps': 'هایتي', 'ur': 'ہیٹی'}),
  Country(isoCode: 'HN', dialCode: '504', nameEn: 'Honduras', maxLength: 8, translations: {'fa': 'هندوراس', 'ar': 'هندوراس', 'ps': 'هوندوراس', 'ur': 'ہونڈوراس'}),
  Country(isoCode: 'HK', dialCode: '852', nameEn: 'Hong Kong', maxLength: 8, translations: {'fa': 'هنگ‌کنگ', 'ar': 'هونغ كونغ', 'ps': 'هانګ کانګ', 'ur': 'ہانگ کانگ'}),
  Country(isoCode: 'HU', dialCode: '36', nameEn: 'Hungary', maxLength: 9, translations: {'fa': 'مجارستان', 'ar': 'المجر', 'ps': 'هنګري', 'ur': 'ہنگری'}),
  Country(isoCode: 'IS', dialCode: '354', nameEn: 'Iceland', maxLength: 7, translations: {'fa': 'ایسلند', 'ar': 'آيسلندا', 'ps': 'آیسلېنډ', 'ur': 'آئس لینڈ'}),
  Country(isoCode: 'IN', dialCode: '91', nameEn: 'India', maxLength: 10, translations: {'fa': 'هند', 'ar': 'الهند', 'ps': 'هند', 'ur': 'بھارت'}),
  Country(isoCode: 'ID', dialCode: '62', nameEn: 'Indonesia', maxLength: 11, translations: {'fa': 'اندونزی', 'ar': 'إندونيسيا', 'ps': 'اندونیزیا', 'ur': 'انڈونیشیا'}),
  Country(isoCode: 'IR', dialCode: '98', nameEn: 'Iran', maxLength: 10, translations: {'fa': 'ایران', 'ar': 'إيران', 'ps': 'ایران', 'ur': 'ایران'}),
  Country(isoCode: 'IQ', dialCode: '964', nameEn: 'Iraq', maxLength: 10, translations: {'fa': 'عراق', 'ar': 'العراق', 'ps': 'عراق', 'ur': 'عراق'}),
  Country(isoCode: 'IE', dialCode: '353', nameEn: 'Ireland', maxLength: 9, translations: {'fa': 'ایرلند', 'ar': 'أيرلندا', 'ps': 'آیرلینډ', 'ur': 'آئرلینڈ'}),
  Country(isoCode: 'IL', dialCode: '972', nameEn: 'Israel', maxLength: 9, translations: {'fa': 'اسرائیل', 'ar': 'إسرائيل', 'ps': 'اسراییل', 'ur': 'اسرائیل'}),
  Country(isoCode: 'IT', dialCode: '39', nameEn: 'Italy', maxLength: 10, translations: {'fa': 'ایتالیا', 'ar': 'إيطاليا', 'ps': 'ایټالیا', 'ur': 'اٹلی'}),
  Country(isoCode: 'JM', dialCode: '1876', nameEn: 'Jamaica', maxLength: 10, translations: {'fa': 'جامائیکا', 'ar': 'جامايكا', 'ps': 'جمایکا', 'ur': 'جمیکا'}),
  Country(isoCode: 'JP', dialCode: '81', nameEn: 'Japan', maxLength: 10, translations: {'fa': 'ژاپن', 'ar': 'اليابان', 'ps': 'جاپان', 'ur': 'جاپان'}),
  Country(isoCode: 'JO', dialCode: '962', nameEn: 'Jordan', maxLength: 9, translations: {'fa': 'اردن', 'ar': 'الأردن', 'ps': 'اردن', 'ur': 'اردن'}),
  Country(isoCode: 'KZ', dialCode: '7', nameEn: 'Kazakhstan', maxLength: 10, translations: {'fa': 'قزاقستان', 'ar': 'كازاخستان', 'ps': 'قزاقستان', 'ur': 'قازقستان'}),
  Country(isoCode: 'KE', dialCode: '254', nameEn: 'Kenya', maxLength: 10, translations: {'fa': 'کنیا', 'ar': 'كينيا', 'ps': 'کینیا', 'ur': 'کینیا'}),
  Country(isoCode: 'KW', dialCode: '965', nameEn: 'Kuwait', maxLength: 8, translations: {'fa': 'کویت', 'ar': 'الكويت', 'ps': 'کویت', 'ur': 'کویت'}),
  Country(isoCode: 'KG', dialCode: '996', nameEn: 'Kyrgyzstan', maxLength: 9, translations: {'fa': 'قرقیزستان', 'ar': 'قيرغيزستان', 'ps': 'قرغیزستان', 'ur': 'کرغزستان'}),
  Country(isoCode: 'LA', dialCode: '856', nameEn: 'Laos', maxLength: 10, translations: {'fa': 'لائوس', 'ar': 'لاوس', 'ps': 'لاوس', 'ur': 'لاؤس'}),
  Country(isoCode: 'LV', dialCode: '371', nameEn: 'Latvia', maxLength: 8, translations: {'fa': 'لتونی', 'ar': 'لاتفيا', 'ps': 'لاتویا', 'ur': 'لٹویا'}),
  Country(isoCode: 'LB', dialCode: '961', nameEn: 'Lebanon', maxLength: 8, translations: {'fa': 'لبنان', 'ar': 'لبنان', 'ps': 'لبنان', 'ur': 'لبنان'}),
  Country(isoCode: 'LY', dialCode: '218', nameEn: 'Libya', maxLength: 9, translations: {'fa': 'لیبی', 'ar': 'ليبيا', 'ps': 'لیبیا', 'ur': 'لیبیا'}),
  Country(isoCode: 'LI', dialCode: '423', nameEn: 'Liechtenstein', maxLength: 7, translations: {'fa': 'لیختن‌اشتاین', 'ar': 'ليختنشتاين', 'ps': 'لیخټنشتاین', 'ur': 'لیختینستائن'}),
  Country(isoCode: 'LT', dialCode: '370', nameEn: 'Lithuania', maxLength: 8, translations: {'fa': 'لیتوانی', 'ar': 'ليتوانيا', 'ps': 'لیتوانیا', 'ur': 'لتھوانیا'}),
  Country(isoCode: 'LU', dialCode: '352', nameEn: 'Luxembourg', maxLength: 9, translations: {'fa': 'لوکزامبورگ', 'ar': 'لوكسمبورغ', 'ps': 'لوکسامبورګ', 'ur': 'لکسمبرگ'}),
  Country(isoCode: 'MO', dialCode: '853', nameEn: 'Macau', maxLength: 8, translations: {'fa': 'ماکائو', 'ar': 'ماكاو', 'ps': 'ماکاو', 'ur': 'مکاؤ'}),
  Country(isoCode: 'MK', dialCode: '389', nameEn: 'North Macedonia', maxLength: 8, translations: {'fa': 'مقدونیه شمالی', 'ar': 'مقدونيا الشمالية', 'ps': 'شمالي مقدونیه', 'ur': 'شمالی مقدونیہ'}),
  Country(isoCode: 'MG', dialCode: '261', nameEn: 'Madagascar', maxLength: 9, translations: {'fa': 'ماداگاسکار', 'ar': 'مدغشقر', 'ps': 'مادګاسکر', 'ur': 'مڈغاسکر'}),
  Country(isoCode: 'MW', dialCode: '265', nameEn: 'Malawi', maxLength: 9, translations: {'fa': 'مالاوی', 'ar': 'مالاوي', 'ps': 'ملاوي', 'ur': 'ملاوی'}),
  Country(isoCode: 'MY', dialCode: '60', nameEn: 'Malaysia', maxLength: 10, translations: {'fa': 'مالزی', 'ar': 'ماليزيا', 'ps': 'مالېزیا', 'ur': 'ملائیشیا'}),
  Country(isoCode: 'MV', dialCode: '960', nameEn: 'Maldives', maxLength: 7, translations: {'fa': 'مالدیو', 'ar': 'جزر المالديف', 'ps': 'مالدیوی', 'ur': 'مالدیپ'}),
  Country(isoCode: 'ML', dialCode: '223', nameEn: 'Mali', maxLength: 8, translations: {'fa': 'مالی', 'ar': 'مالي', 'ps': 'مالي', 'ur': 'مالی'}),
  Country(isoCode: 'MT', dialCode: '356', nameEn: 'Malta', maxLength: 8, translations: {'fa': 'مالت', 'ar': 'مالطا', 'ps': 'مالټا', 'ur': 'مالٹا'}),
  Country(isoCode: 'MR', dialCode: '222', nameEn: 'Mauritania', maxLength: 8, translations: {'fa': 'موریتانی', 'ar': 'موريتانيا', 'ps': 'موریتانیا', 'ur': 'موریتانیہ'}),
  Country(isoCode: 'MX', dialCode: '52', nameEn: 'Mexico', maxLength: 10, translations: {'fa': 'مکزیک', 'ar': 'المكسيك', 'ps': 'مکسیکو', 'ur': 'میکسیکو'}),
  Country(isoCode: 'MD', dialCode: '373', nameEn: 'Moldova', maxLength: 8, translations: {'fa': 'مولداوی', 'ar': 'مولدوفا', 'ps': 'مولدوا', 'ur': 'مالدووا'}),
  Country(isoCode: 'MC', dialCode: '377', nameEn: 'Monaco', maxLength: 8, translations: {'fa': 'موناکو', 'ar': 'موناكو', 'ps': 'موناکو', 'ur': 'موناکو'}),
  Country(isoCode: 'MN', dialCode: '976', nameEn: 'Mongolia', maxLength: 8, translations: {'fa': 'مغولستان', 'ar': 'منغوليا', 'ps': 'مغولستان', 'ur': 'منگولیا'}),
  Country(isoCode: 'ME', dialCode: '382', nameEn: 'Montenegro', maxLength: 8, translations: {'fa': 'مونته‌نگرو', 'ar': 'الجبل الأسود', 'ps': 'مونتينیګرو', 'ur': 'مونٹینیگرو'}),
  Country(isoCode: 'MA', dialCode: '212', nameEn: 'Morocco', maxLength: 9, translations: {'fa': 'مراکش', 'ar': 'المغرب', 'ps': 'مراکش', 'ur': 'مراکش'}),
  Country(isoCode: 'MZ', dialCode: '258', nameEn: 'Mozambique', maxLength: 9, translations: {'fa': 'موزامبیک', 'ar': 'موزمبيق', 'ps': 'موزمبیک', 'ur': 'موزمبیق'}),
  Country(isoCode: 'MM', dialCode: '95', nameEn: 'Myanmar', maxLength: 9, translations: {'fa': 'میانمار', 'ar': 'ميانمار', 'ps': 'میانمار', 'ur': 'میانمار'}),
  Country(isoCode: 'NA', dialCode: '264', nameEn: 'Namibia', maxLength: 9, translations: {'fa': 'نامیبیا', 'ar': 'ناميبيا', 'ps': 'نمیبیا', 'ur': 'نمیبیا'}),
  Country(isoCode: 'NP', dialCode: '977', nameEn: 'Nepal', maxLength: 10, translations: {'fa': 'نپال', 'ar': 'نيبال', 'ps': 'نیپال', 'ur': 'نیپال'}),
  Country(isoCode: 'NL', dialCode: '31', nameEn: 'Netherlands', maxLength: 9, translations: {'fa': 'هلند', 'ar': 'هولندا', 'ps': 'هالېنډ', 'ur': 'نیدرلینڈز'}),
  Country(isoCode: 'NZ', dialCode: '64', nameEn: 'New Zealand', maxLength: 9, translations: {'fa': 'نیوزیلند', 'ar': 'نيوزيلندا', 'ps': 'نیوزیلنډ', 'ur': 'نیوزی لینڈ'}),
  Country(isoCode: 'NI', dialCode: '505', nameEn: 'Nicaragua', maxLength: 8, translations: {'fa': 'نیکاراگوئه', 'ar': 'نيكاراغوا', 'ps': 'نیکاراګوا', 'ur': 'نکاراگوا'}),
  Country(isoCode: 'NE', dialCode: '227', nameEn: 'Niger', maxLength: 8, translations: {'fa': 'نیجر', 'ar': 'النيجر', 'ps': 'نایجر', 'ur': 'نائیجر'}),
  Country(isoCode: 'NG', dialCode: '234', nameEn: 'Nigeria', maxLength: 10, translations: {'fa': 'نیجریه', 'ar': 'نيجيريا', 'ps': 'نایجېریا', 'ur': 'نائیجیریا'}),
  Country(isoCode: 'NO', dialCode: '47', nameEn: 'Norway', maxLength: 8, translations: {'fa': 'نروژ', 'ar': 'النرويج', 'ps': 'ناروی', 'ur': 'ناروے'}),
  Country(isoCode: 'OM', dialCode: '968', nameEn: 'Oman', maxLength: 8, translations: {'fa': 'عمان', 'ar': 'عُمان', 'ps': 'عمان', 'ur': 'عمان'}),
  Country(isoCode: 'PK', dialCode: '92', nameEn: 'Pakistan', maxLength: 10, translations: {'fa': 'پاکستان', 'ar': 'باكستان', 'ps': 'پاکستان', 'ur': 'پاکستان'}),
  Country(isoCode: 'PS', dialCode: '970', nameEn: 'Palestine', maxLength: 9, translations: {'fa': 'فلسطین', 'ar': 'فلسطين', 'ps': 'فلسطین', 'ur': 'فلسطین'}),
  Country(isoCode: 'PA', dialCode: '507', nameEn: 'Panama', maxLength: 8, translations: {'fa': 'پاناما', 'ar': 'بنما', 'ps': 'پاناما', 'ur': 'پانامہ'}),
  Country(isoCode: 'PY', dialCode: '595', nameEn: 'Paraguay', maxLength: 9, translations: {'fa': 'پاراگوئه', 'ar': 'باراغواي', 'ps': 'پاراګوای', 'ur': 'پیراگوئے'}),
  Country(isoCode: 'PE', dialCode: '51', nameEn: 'Peru', maxLength: 9, translations: {'fa': 'پرو', 'ar': 'بيرو', 'ps': 'پیرو', 'ur': 'پیرو'}),
  Country(isoCode: 'PH', dialCode: '63', nameEn: 'Philippines', maxLength: 10, translations: {'fa': 'فیلیپین', 'ar': 'الفلبين', 'ps': 'فلیپین', 'ur': 'فلپائن'}),
  Country(isoCode: 'PL', dialCode: '48', nameEn: 'Poland', maxLength: 9, translations: {'fa': 'لهستان', 'ar': 'بولندا', 'ps': 'پولنډ', 'ur': 'پولینڈ'}),
  Country(isoCode: 'PT', dialCode: '351', nameEn: 'Portugal', maxLength: 9, translations: {'fa': 'پرتغال', 'ar': 'البرتغال', 'ps': 'پورتګال', 'ur': 'پرتگال'}),
  Country(isoCode: 'QA', dialCode: '974', nameEn: 'Qatar', maxLength: 8, translations: {'fa': 'قطر', 'ar': 'قطر', 'ps': 'قطر', 'ur': 'قطر'}),
  Country(isoCode: 'RO', dialCode: '40', nameEn: 'Romania', maxLength: 9, translations: {'fa': 'رومانی', 'ar': 'رومانيا', 'ps': 'رومانیا', 'ur': 'رومانیہ'}),
  Country(isoCode: 'RU', dialCode: '7', nameEn: 'Russia', maxLength: 10, translations: {'fa': 'روسیه', 'ar': 'روسيا', 'ps': 'روسیه', 'ur': 'روس'}),
  Country(isoCode: 'RW', dialCode: '250', nameEn: 'Rwanda', maxLength: 9, translations: {'fa': 'رواندا', 'ar': 'رواندا', 'ps': 'روندا', 'ur': 'روانڈا'}),
  Country(isoCode: 'SA', dialCode: '966', nameEn: 'Saudi Arabia', maxLength: 9, translations: {'fa': 'عربستان سعودی', 'ar': 'المملكة العربية السعودية', 'ps': 'سعودي عربستان', 'ur': 'سعودی عرب'}),
  Country(isoCode: 'SN', dialCode: '221', nameEn: 'Senegal', maxLength: 9, translations: {'fa': 'سنگال', 'ar': 'السنغال', 'ps': 'سنیګال', 'ur': 'سینیگال'}),
  Country(isoCode: 'RS', dialCode: '381', nameEn: 'Serbia', maxLength: 9, translations: {'fa': 'صربستان', 'ar': 'صربيا', 'ps': 'سربیا', 'ur': 'سربیا'}),
  Country(isoCode: 'SG', dialCode: '65', nameEn: 'Singapore', maxLength: 8, translations: {'fa': 'سنگاپور', 'ar': 'سنغافورة', 'ps': 'سینګاپور', 'ur': 'سنگاپور'}),
  Country(isoCode: 'SK', dialCode: '421', nameEn: 'Slovakia', maxLength: 9, translations: {'fa': 'اسلواکی', 'ar': 'سلوفاكيا', 'ps': 'سلواکیا', 'ur': 'سلوواکیہ'}),
  Country(isoCode: 'SI', dialCode: '386', nameEn: 'Slovenia', maxLength: 8, translations: {'fa': 'اسلوونی', 'ar': 'سلوفينيا', 'ps': 'سلوانیا', 'ur': 'سلووینیا'}),
  Country(isoCode: 'SO', dialCode: '252', nameEn: 'Somalia', maxLength: 8, translations: {'fa': 'سومالی', 'ar': 'الصومال', 'ps': 'سومالیا', 'ur': 'صومالیہ'}),
  Country(isoCode: 'ZA', dialCode: '27', nameEn: 'South Africa', maxLength: 9, translations: {'fa': 'آفریقای جنوبی', 'ar': 'جنوب أفريقيا', 'ps': 'سویلي افریقا', 'ur': 'جنوبی افریقہ'}),
  Country(isoCode: 'KR', dialCode: '82', nameEn: 'South Korea', maxLength: 10, translations: {'fa': 'کره جنوبی', 'ar': 'كوريا الجنوبية', 'ps': 'سویلي کوریا', 'ur': 'جنوبی کوریا'}),
  Country(isoCode: 'SS', dialCode: '211', nameEn: 'South Sudan', maxLength: 9, translations: {'fa': 'سودان جنوبی', 'ar': 'جنوب السودان', 'ps': 'سویلي سوډان', 'ur': 'جنوبی سوڈان'}),
  Country(isoCode: 'ES', dialCode: '34', nameEn: 'Spain', maxLength: 9, translations: {'fa': 'اسپانیا', 'ar': 'إسبانيا', 'ps': 'هسپانیه', 'ur': 'ہسپانیہ'}),
  Country(isoCode: 'LK', dialCode: '94', nameEn: 'Sri Lanka', maxLength: 9, translations: {'fa': 'سریلانکا', 'ar': 'سريلانكا', 'ps': 'سریلانکا', 'ur': 'سری لنکا'}),
  Country(isoCode: 'SD', dialCode: '249', nameEn: 'Sudan', maxLength: 9, translations: {'fa': 'سودان', 'ar': 'السودان', 'ps': 'سوډان', 'ur': 'سوڈان'}),
  Country(isoCode: 'SR', dialCode: '597', nameEn: 'Suriname', maxLength: 7, translations: {'fa': 'سورینام', 'ar': 'سورينام', 'ps': 'سورینام', 'ur': 'سورینام'}),
  Country(isoCode: 'SE', dialCode: '46', nameEn: 'Sweden', maxLength: 9, translations: {'fa': 'سوئد', 'ar': 'السويد', 'ps': 'سویډن', 'ur': 'سویڈن'}),
  Country(isoCode: 'CH', dialCode: '41', nameEn: 'Switzerland', maxLength: 9, translations: {'fa': 'سوئیس', 'ar': 'سويسرا', 'ps': 'سویس', 'ur': 'سوئٹزرلینڈ'}),
  Country(isoCode: 'SY', dialCode: '963', nameEn: 'Syria', maxLength: 9, translations: {'fa': 'سوریه', 'ar': 'سوريا', 'ps': 'سوریه', 'ur': 'شام'}),
  Country(isoCode: 'TW', dialCode: '886', nameEn: 'Taiwan', maxLength: 9, translations: {'fa': 'تایوان', 'ar': 'تايوان', 'ps': 'تایوان', 'ur': 'تائیوان'}),
  Country(isoCode: 'TJ', dialCode: '992', nameEn: 'Tajikistan', maxLength: 9, translations: {'fa': 'تاجیکستان', 'ar': 'طاجيكستان', 'ps': 'تاجکستان', 'ur': 'تاجکستان'}),
  Country(isoCode: 'TZ', dialCode: '255', nameEn: 'Tanzania', maxLength: 9, translations: {'fa': 'تانزانیا', 'ar': 'تنزانيا', 'ps': 'تانزانیا', 'ur': 'تنزانیہ'}),
  Country(isoCode: 'TH', dialCode: '66', nameEn: 'Thailand', maxLength: 9, translations: {'fa': 'تایلند', 'ar': 'تايلاند', 'ps': 'تایلنډ', 'ur': 'تھائی لینڈ'}),
  Country(isoCode: 'TG', dialCode: '228', nameEn: 'Togo', maxLength: 8, translations: {'fa': 'توگو', 'ar': 'توغو', 'ps': 'توګو', 'ur': 'ٹوگو'}),
  Country(isoCode: 'TN', dialCode: '216', nameEn: 'Tunisia', maxLength: 8, translations: {'fa': 'تونس', 'ar': 'تونس', 'ps': 'تونس', 'ur': 'تیونس'}),
  Country(isoCode: 'TR', dialCode: '90', nameEn: 'Turkey', maxLength: 10, translations: {'fa': 'ترکیه', 'ar': 'تركيا', 'ps': 'ترکیه', 'ur': 'ترکی'}),
  Country(isoCode: 'TM', dialCode: '993', nameEn: 'Turkmenistan', maxLength: 8, translations: {'fa': 'ترکمنستان', 'ar': 'تركمانستان', 'ps': 'ترکمنستان', 'ur': 'ترکمانستان'}),
  Country(isoCode: 'UG', dialCode: '256', nameEn: 'Uganda', maxLength: 9, translations: {'fa': 'اوگاندا', 'ar': 'أوغندا', 'ps': 'یوګانډا', 'ur': 'یوگنڈا'}),
  Country(isoCode: 'UA', dialCode: '380', nameEn: 'Ukraine', maxLength: 9, translations: {'fa': 'اوکراین', 'ar': 'أوكرانيا', 'ps': 'اوکراین', 'ur': 'یوکرین'}),
  Country(isoCode: 'AE', dialCode: '971', nameEn: 'United Arab Emirates', maxLength: 9, translations: {'fa': 'امارات متحده عربی', 'ar': 'الإمارات العربية المتحدة', 'ps': 'متحده عرب امارات', 'ur': 'متحدہ عرب امارات'}),
  Country(isoCode: 'GB', dialCode: '44', nameEn: 'United Kingdom', maxLength: 10, translations: {'fa': 'بریتانیا', 'ar': 'المملكة المتحدة', 'ps': 'متحده پاچاهي', 'ur': 'برطانیہ'}),
  Country(isoCode: 'US', dialCode: '1', nameEn: 'United States', maxLength: 10, translations: {'fa': 'ایالات متحده', 'ar': 'الولايات المتحدة', 'ps': 'متحده ایالات', 'ur': 'ریاستہائے متحدہ امریکہ'}),
  Country(isoCode: 'UY', dialCode: '598', nameEn: 'Uruguay', maxLength: 8, translations: {'fa': 'اروگوئه', 'ar': 'الأوروغواي', 'ps': 'یوروګوای', 'ur': 'یوراگوئے'}),
  Country(isoCode: 'UZ', dialCode: '998', nameEn: 'Uzbekistan', maxLength: 9, translations: {'fa': 'ازبکستان', 'ar': 'أوزبكستان', 'ps': 'ازبکستان', 'ur': 'ازبکستان'}),
  Country(isoCode: 'VE', dialCode: '58', nameEn: 'Venezuela', maxLength: 10, translations: {'fa': 'ونزوئلا', 'ar': 'فنزويلا', 'ps': 'ونزویلا', 'ur': 'وینزویلا'}),
  Country(isoCode: 'VN', dialCode: '84', nameEn: 'Vietnam', maxLength: 9, translations: {'fa': 'ویتنام', 'ar': 'فيتنام', 'ps': 'ویتنام', 'ur': 'ویتنام'}),
  Country(isoCode: 'YE', dialCode: '967', nameEn: 'Yemen', maxLength: 9, translations: {'fa': 'یمن', 'ar': 'اليمن', 'ps': 'یمن', 'ur': 'یمن'}),
  Country(isoCode: 'ZM', dialCode: '260', nameEn: 'Zambia', maxLength: 9, translations: {'fa': 'زامبیا', 'ar': 'زامبيا', 'ps': 'زمبیا', 'ur': 'زیمبیا'}),
  Country(isoCode: 'ZW', dialCode: '263', nameEn: 'Zimbabwe', maxLength: 9, translations: {'fa': 'زیمبابوه', 'ar': 'زيمبابوي', 'ps': 'زیمبابوی', 'ur': 'زمبابوے'}),
];

/// ISO codes for languages that are written right-to-left. Used by the
/// widget to auto-mirror layout/text direction; override at will via
/// `PhoneFormField.rtlLocales` or by forcing `textDirection` yourself.
const Set<String> defaultRtlLocales = {'fa', 'ar', 'ps', 'ur', 'he', 'dv', 'ku'};
